### ISSUE TITLE
Content is not allowed in prolog.

### ISSUE THREAD

**Issue by Snaville** [sa3dany/android-sms-hooks#6]
I need help, i am opening the project for the first time in Android Studio but i am facing  this error:

```
ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
```

How can i solve this because i cant find cause of this error.

**Comment by sa3dany** [comment]
Hey @Snaville, I just did a clone from master and opened the project in the latest version of Android Studio `2020.3.1` with no issues.
